# Generated by Django 5.1.2 on 2024-10-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMPLOYEE', '0002_department_name_az_department_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
