# Generated by Django 5.1.2 on 2024-11-02 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMPLOYEE', '0008_subscribers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribers',
        ),
    ]
