# Generated by Django 5.1.2 on 2024-11-04 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMPLOYEE', '0012_alter_employee_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='surname',
            new_name='last_name',
        ),
    ]
