# Generated by Django 5.1.2 on 2024-11-04 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMPLOYEE', '0013_rename_name_employee_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='last_name',
            new_name='surname',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
