# Generated by Django 5.1.2 on 2024-11-04 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMPLOYEE', '0015_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
